version: '3.8'

networks:
  postgres:
    name: postgres
    driver: bridge

services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - postgres

  admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgres
